services:
  dashboard:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./data:/app/data
      - ./static:/app/static
      - ./pages:/app/pages
      - ./templates:/app/templates
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 