services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./pages:/app/pages
      - ./templates:/app/templates
      - ./VERSION:/app/VERSION
      - ./CHANGELOG.md:/app/CHANGELOG.md
      - ./dashboard.db:/app/dashboard.db
      - ./logs:/app/logs
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 