name: Update Version Badge

on:
  push:
    paths:
      - 'VERSION'
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Read version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Update README with version badge
        run: |
          # Create the badge URL
          BADGE_URL="https://img.shields.io/badge/version-${{ steps.version.outputs.version }}-blue.svg"
          
          # Check if badge already exists and update it, or add new one
          if grep -q "badge/version-" README.md; then
            # Update existing badge
            sed -i "s/badge\/version-[^)]*/badge\/version-${{ steps.version.outputs.version }}/g" README.md
          else
            # Add new badge after title
            sed -i "2i\\
          ![Version](https://img.shields.io/badge/version-${{ steps.version.outputs.version }}-blue.svg)\\
          " README.md
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update version badge to ${{ steps.version.outputs.version }}"
            git push
          fi 